#!/usr/bin/python3
from sys import argv
from src.error_handling import *
from src.maths import *

def main(args):
    nb_args = len(args)

    if nb_args == 3:
        case1(args)
        exit(0)
    elif nb_args == 4:
        case2(args)
        exit(0)
    elif nb_args == 2 and args[1] == "-h":
        print("USAGE\n\t./106bombyx n [k | i0 i1]\nDESCRIPTION\n\tn\tnumber of first generation individuals\n\tk\tgrowth rate from 1 to 4\n\ti0\tinitial generation (included)\n\ti1\tfinal generation (included)")
        exit(0)
    else:
        display_error("Wrong argument number (try \"-h\" to display help)")
        exit(84)

if __name__ == '__main__':
    main(argv)
